/**
 * Import SARIMA Model Forecasts to MongoDB
 * =========================================
 * 
 * This script imports rainfall forecasts generated by the Python SARIMA model
 * (backend/ml/sarima_rainfall_model.py) into MongoDB.
 * 
 * Prerequisites:
 *   1. Run the Python training script first:
 *      cd backend/ml && python sarima_rainfall_model.py
 *   2. This generates: backend/ml/forecasts/rainfall_forecasts.json
 * 
 * Usage:
 *   node scripts/importSarimaForecasts.js
 */

const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
require('dotenv').config();

const RainfallForecast = require('../models/RainfallForecast');

// MongoDB connection
const connectDB = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/RubberEco';
    await mongoose.connect(mongoUri);
    console.log('✅ Connected to MongoDB');
  } catch (error) {
    console.error('❌ MongoDB connection error:', error);
    process.exit(1);
  }
};

// Load forecasts from Python-generated JSON
const loadSarimaForecasts = () => {
  const forecastsPath = path.join(__dirname, '..', 'ml', 'forecasts', 'rainfall_forecasts.json');
  
  if (!fs.existsSync(forecastsPath)) {
    console.error('❌ Forecasts file not found!');
    console.error('   Please run the Python SARIMA training script first:');
    console.error('   cd backend/ml && python sarima_rainfall_model.py');
    process.exit(1);
  }
  
  const rawData = fs.readFileSync(forecastsPath, 'utf8');
  return JSON.parse(rawData);
};

// Load model metadata
const loadModelMetadata = () => {
  const metadataPath = path.join(__dirname, '..', 'ml', 'trained_models', 'model_metadata.json');
  
  if (fs.existsSync(metadataPath)) {
    const rawData = fs.readFileSync(metadataPath, 'utf8');
    return JSON.parse(rawData);
  }
  
  return null;
};

const importSarimaForecasts = async () => {
  try {
    console.log('🌧️  Loading SARIMA rainfall forecasts...');
    
    const forecasts = loadSarimaForecasts();
    const metadata = loadModelMetadata();
    
    if (metadata) {
      console.log('\n📊 Model Information:');
      console.log(`   - Model Type: ${metadata.model_type}`);
      console.log(`   - Order: ARIMA${JSON.stringify(metadata.order)}`);
      console.log(`   - Training Period: ${metadata.training_years}`);
      console.log(`   - AIC: ${metadata.aic?.toFixed(2) || 'N/A'}`);
      console.log(`   - RMSE: ${metadata.metrics?.rmse?.toFixed(2) || 'N/A'} mm`);
      console.log(`   - Trained At: ${metadata.trained_at}`);
    }
    
    console.log(`\n📝 Processing ${forecasts.length} records...`);
    
    // Prepare bulk operations
    const bulkOps = forecasts.map(record => {
      const doc = {
        year: record.year,
        state: record.state || 'Kerala',
        season: record.season || 'Monsoon',
        months: record.months || ['June', 'July', 'August', 'September'],
        predictedRainfall: record.predictedRainfall,
        riskLevel: record.riskLevel,
        model: record.model,
        isForecast: record.isForecast || false,
        // Include confidence intervals for forecasts
        ...(record.lowerCI && { lowerCI: record.lowerCI }),
        ...(record.upperCI && { upperCI: record.upperCI }),
        createdAt: new Date()
      };
      
      return {
        updateOne: {
          filter: { year: record.year, season: 'Monsoon' },
          update: { $set: doc },
          upsert: true
        }
      };
    });
    
    // Execute bulk write
    const result = await RainfallForecast.bulkWrite(bulkOps);
    
    console.log('\n✅ SARIMA forecasts imported successfully!');
    console.log(`   - Matched: ${result.matchedCount}`);
    console.log(`   - Modified: ${result.modifiedCount}`);
    console.log(`   - Upserted: ${result.upsertedCount}`);
    
    // Log summary of forecast years
    const forecastYears = forecasts.filter(r => r.isForecast);
    if (forecastYears.length > 0) {
      console.log(`\n🔮 Forecast years (${forecastYears.length}):`);
      forecastYears.forEach(f => {
        const riskEmoji = { High: '🔴', Normal: '🟢', Low: '🟡' }[f.riskLevel] || '⚪';
        console.log(`   ${f.year}: ${f.predictedRainfall.toFixed(2)} mm ${riskEmoji} ${f.riskLevel}`);
      });
    }
    
  } catch (error) {
    console.error('❌ Error importing SARIMA forecasts:', error);
    throw error;
  }
};

const run = async () => {
  console.log('=' .repeat(60));
  console.log('🌧️  SARIMA RAINFALL FORECAST IMPORT');
  console.log('=' .repeat(60));
  
  await connectDB();
  await importSarimaForecasts();
  await mongoose.connection.close();
  
  console.log('\n🔌 Database connection closed');
  console.log('=' .repeat(60));
  process.exit(0);
};

if (require.main === module) {
  run();
}

module.exports = { importSarimaForecasts };

